package com.prograngers.backend.exception;

public enum ErrorCode {
    INVALID_REQUEST_BODY,
    SOLUTION_NOT_FOUND,
    PROBLEM_NOT_FOUND,
    PROBLEM_LINK_NOT_FOUND,
    COMMENT_NOT_FOUND,
    ALGORITHM_NOT_EXISTS,
    DATA_STRUCTURE_NOT_EXISTS,
    LEVEL_NOT_EXISTS;

}
