package com.prograngers.backend.exception;

public enum ErrorCode {
    INVALID_REQUEST_BODY,
    SOLUTION_NOT_FOUND,
    PROBLEM_NOT_FOUND,
    PROBLEM_LINK_NOT_FOUND,
    COMMENT_NOT_FOUND,
    ALGORITHM_NOT_EXISTS,
    DATASTRUCTURE_NOT_EXISTS,
    LEVEL_NOT_EXISTS,
    MEMBER_NOT_FOUND,
    INVALID_PASSWORD,
    EXPIRED_TOKEN,
    NOT_EXIST_TOKEN,
    FAIL_TO_ENCODED,
    FAIL_TO_DECODED,
    NOT_FOUND_REFRESH_TOKEN,
    NOT_EXIST_REFRESH_TOKEN,
    LANGUAGE_NOT_EXISTS,
    INCORRECT_PASSWORD,
    UNAUTHORIZED_MEMBER;

}
