package com.prograngers.backend.exception;

public enum ErrorCode {

    INVALID_SOLUTION_BODY,
    SOLUTION_NOT_FOUND,
    PROBLEM_LINK_NOT_FOUND,
    ALGORITHM_NOT_EXISTS,
    DATASTRUCTURE_NOT_EXISTS,
    LEVEL_NOT_EXISTS,
    MEMBER_NOT_FOUND,
    INVALID_PASSWORD,
    EXPIRED_TOKEN;

}
