export { MainPage } from './MainPage';
export { NotFound } from './NotFound';
export { Problems } from './Problems';
export { Profile } from './Profile';
export { SignIn } from './Auth';
export { SignUp } from './Auth';
export { Solutions } from './Solutions';
export { SolutionDetail } from './SolutionDetail';
export { MyPage } from './MyPage';
export { RegisterReview } from './RegisterReview'
export { Account } from './Account/Account'
export { AccountChange } from './Account/AccountChange'
export { MySolution } from './MySolution'
export { MyComment } from './MyComment/MyComment'
export { Like } from './Like/Like'
export { Follow } from './Follow/Follow'