export { MainPage } from './MainPage';
export { NotFound } from './NotFound';
export { Problems } from './Problems';
export { Profile } from './Profile';
export { SignIn } from './SignIn';
export { SignUp } from './SignUp';
export { Solutions } from './Solutions';
export { SolutionDetail } from './SolutionDetail';
export { MyPage } from './MyPage';
export { RegisterReview } from './RegisterReview'
export { Account } from './Account'
export { MySolution } from './MySolution'
export { MyComment } from './MyComment'
export { Like } from './Like'
export { Follow } from './Follow'